Flight_booker/config/routes.rb
Rails.application.routes.draw do
  
  root'flights#index'
  get '/flights', to: 'flights#index'
  resources :bookings, only: [:new, :create, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Flight_booker/app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: "Flight"
  has_many :arriving_flights,  class_name: "Flight"
end

Flight_booker/app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, dependent: :destroy
  
  accepts_nested_attributes_for :passengers
end

Flight_booker/app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: "Airport", foreign_key: "from", dependent: :destroy
  belongs_to :to_airport,   class_name: "Airport", foreign_key: "to",   dependent: :destroy
  has_many :bookings
  has_many :passengers, through: :bookings
end

Flight_booker/app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  
  validates :name,  presence: true
  validates :email, presence: true
end

Flight_booker/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    flight = Flight.find(params[:flight][:flight_id])
    @booking = flight.bookings.build
    params[:num_tickets].to_i.times do
      @booking.passengers.build
    end
  end
  
  def create
    flight = Flight.find(params[:booking][:flight_id])
    @booking = flight.bookings.build(booking_params)
    if @booking.save
      send_emails(@booking.passengers)
      redirect_to @booking
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end
  
   private

    def booking_params
      params.require(:booking).permit(passengers_attributes: [:name, :email])
    end
    
    def send_emails(passengers)
      passengers.each do |passenger|
        PassengerMailer.thank_you(passenger).deliver_now
      end
    end
end

Flight_booker/app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  
  def index
    @airports = Airport.all.map { |airport| [airport.code, airport.id] }
    dates = Flight.all.map { |flight| flight.datetime.strftime("%Y-%m-%d") }
    @flight_dates = dates.uniq.sort_by { |d| d.split(?/).rotate(-1).map { |e| -e.to_i } }
    @passengers = [1, 2, 3, 4]
    
    @from = params[:from_code]
    @to = params[:to_code]
    @date = params[:date]
    @tickets = params[:num_tickets]
    
    @flights = Flight.where(from: @from, to: @to, datetime: @date)
  end
end

Flight_booker/app/helpers/bookings_helper.rb
module BookingsHelper
end

Flight_booker/app/helpers/flights_helper.rb
module FlightsHelper
end

Flight_booker/app/views/bookings/new.html.erb
<h2>Your flight</h2>
<table>
  <th></th>
  <th>Flight number</th>
  <th>Departing</th>
  <th>Arriving</th>
  <th>Date</th>
  <th>Flight Duration</th>
    <tr>
      <td><%= @booking.flight.id %></td>
      <td><%= @booking.flight.from_airport.code %></td>
      <td><%= @booking.flight.to_airport.code %></td>
      <td><%= @booking.flight.datetime %></td>
      <td><%= @booking.flight.duration %></td>
    </tr>
</table>

<%= form_for(@booking, url: bookings_path) do |f| %>
	<%= f.hidden_field :flight_id %>
	
	<% cntr = 0 %>
	<%= f.fields_for(:passengers) do |passenger| %>
		<h3> <%= "Passenger #{cntr += 1} information" %> </h3>
		
		<%= passenger.label :name %>
    <%= passenger.text_field :name %>

    <%= passenger.label :email %>
    <%= passenger.text_field :email %>
	<% end %>
	<%= f.submit "Submit booking" %>
<% end %>

Flight_booker/app/views/bookings/show.html.erb
<h1>Your booking ticket:</h1>
<div>
	<div>
		<ol>
			<li>
				Booking id: <%= @booking.id %>.
			</li>
			<li>			
				Flight id: <%= @booking.flight.id %>.
			</li>
			<li>
				Departure airport: <%= @booking.flight.from_airport.code %>	.	
			</li>
			<li>
				Arrival airport: <%= @booking.flight.to_airport.code %>.
			</li>
			<li>
				Departure date: <%= @booking.flight.datetime %>.
			</li>
			<li>
				Flight duration: <%= @booking.flight.duration %> minutes.
			</li>
			
			<% if @booking.passengers.any? %>
				<h2>Passengers(<%= @booking.passengers.count %>)</h2>
				<% @booking.passengers.each_with_index do |passenger, index| %>	
				<li>		
					Name: <%= passenger.name %> /
					Email: <%= passenger.email %>
				</li>
				<%end%>
			<%end%>
		</ol>
	</div>
</div>
<%= link_to "Search for another flight", root_path %>